version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/postgres'
      NODE_ENV: development
      PORT: 3000

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: test
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data