version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:${API_PORT}:3000'
      - '127.0.0.1:${SOCKET_PORT}:4000'
    depends_on:
      - postgres
    environment:
      TZ: Europe/Paris
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      API_PORT: "${API_PORT}"
      SOCKET_PORT: "${SOCKET_PORT}"
    networks:
      - back
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:14.1-alpine
    networks:
      - back
    environment:
      TZ: Europe/Paris
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./data:/var/lib/postgresql/data

  prisma:
    ports:
      - "127.0.0.1:${PRISMA_PORT}:5555"
    depends_on:
      - postgres
    environment:
      TZ: Europe/Paris
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    networks:
      - back
    build:
      context: src/prisma
      dockerfile: Dockerfile

networks:
 back:
