version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/postgres'
    networks:
      - back
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - back
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  prisma:
    container_name: prisma
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
    build:
      context: src/prisma
      dockerfile: Dockerfile

networks:
 back: