version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}'
      PORT: 3000
    networks:
      - back
    volumes:
      - ./public:/app/public

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - back
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  prisma:
    container_name: prisma
    ports:
      - "127.0.0.1:5555:5555"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}"
    networks:
      - back
    build:
      context: src/prisma
      dockerfile: Dockerfile

networks:
 back:
