-- AlterTable
ALTER TABLE "User" ADD COLUMN     "deviceToken" TEXT NOT NULL DEFAULT E'',
ADD COLUMN     "lastSeenDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastSeenLocationLatitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lastSeenLocationLongitude" DOUBLE PRECISION NOT NULL DEFAULT 0;
