
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
            - "5432:5432"
    environment:
      POSTGRES_DB: dbdropy
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080